spring:
  config:
    import:
      - "classpath:../../../../platform-components/platform-component-cache/src/\
        main/resources/conf/cache.properties"
      - "classpath:conf/kafka.properties"
      - "classpath:../../../../platform-components/platform-component-cache/src/\
        main/resources/conf/redis.properties"
      - "classpath:conf/security.properties"
      - "classpath:conf/thread.properties"